### ISSUE TITLE
Discord link 502 Bad gateaway

### ISSUE THREAD

**Issue by builder-main** [game-ci/documentation#85] opened 2021-02-08 12:15 UTC
Hi I tried to join the discord to discuss but :
![image](https://user-images.githubusercontent.com/32265170/107218216-9d3ce700-6a0f-11eb-99aa-1fc2cd3b3eb8.png)

**Comment by GabLeRoux** [comment] 2021-02-08 17:00
Hi @builder-main I couldn't reproduce this. Where did you click to get this error?

I tried both the discord link on the https://game.ci/docs page and in the top menu section. Both links send me to https://game.ci/discord which redirects correctly to https://discord.com/invite/WyPN5r9

I've searched through the whole codebase and there only seem to be these two places pointing to discord.

I'm closing this issue as I cannot reproduce, but if you have more details on how to reproduce, let me know so we can fix this 👍

Thanks and have an amazing day!

**Comment by builder-main** [comment] 2021-02-08 17:26
Well, it seems issue is now gone. it resolves to discord. Strange indeed

**Comment by GabLeRoux** [comment] 2021-02-08 18:01
I think it happened to you because you managed to click on the link at the exact moment we were deploying the static site and at this point, I don't think there's anything we can do about it.

**Comment by webbertakken** [comment] 2021-02-08 19:19
I observed the same behaviour when I opened this issue.

In fact i'm still experiencing this behaviour right now.

**Comment by GabLeRoux** [comment] 2021-02-08 19:21
Yup, just reproduced too right now. 👀 Should we create a support ticket with Vercel?

**Comment by webbertakken** [comment] 2021-02-08 19:22
![image](https://user-images.githubusercontent.com/20756439/107270491-4ce37a80-6a4b-11eb-9754-2171ee327780.png)

**Comment by GabLeRoux** [comment] 2021-02-08 19:25
For reference: [`discord.js`](https://github.com/game-ci/documentation/blob/main/pages/discord.js)

**Comment by webbertakken** [comment] 2021-02-08 19:28
Right we need to show a layout that doesn't have the searchbar during the redirect.

**Comment by GabLeRoux** [comment] 2021-02-08 19:31
Also, it probably worked for me in the first place due to browser cache. I can reproduce every time in private browsing 👍

**Comment by webbertakken** [comment] 2021-02-08 21:08
closed by #87

**Closed by webbertakken** 2021-02-08 21:08 UTC
Labels: bug
